#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase0
rm -rf *.png *.svg
rm -rf CO2.csv S.csv

#------------------------------------------------------------------------------